### ISSUE TITLE
Python 3.11 includes all files in repo in sdist

### ISSUE THREAD

**Issue by hegjon** [trezor/python-mnemonic#114] opened 2023-08-13 19:35 UTC
Python 3.11 includes all files, but Python 3.7 is installing correct files when generating sdist tarball. Revision f5a975ab10c035596d65d854d21164266ffed284.

### Output from Python 3.11:
```
jonny in python-mnemonic on  master via 🐍 v3.11.4
❯ make clean
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
rm -fr .tox/
rm -f .coverage
rm -fr htmlcov/
rm -fr .pytest_cache

jonny in python-mnemonic on  master via 🐍 v3.11.4
❯ python --version
Python 3.11.4

jonny in python-mnemonic on  master via 🐍 v3.11.4
❯ python setup.py sdist
running sdist
running egg_info
creating src/mnemonic.egg-info
writing src/mnemonic.egg-info/PKG-INFO
writing dependency_links to src/mnemonic.egg-info/dependency_links.txt
writing top-level names to src/mnemonic.egg-info/top_level.txt
writing manifest file 'src/mnemonic.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'src/mnemonic.egg-info/SOURCES.txt'
running check
creating mnemonic-0.20
creating mnemonic-0.20/.github
creating mnemonic-0.20/.github/workflows
creating mnemonic-0.20/src
creating mnemonic-0.20/src/mnemonic
creating mnemonic-0.20/src/mnemonic.egg-info
creating mnemonic-0.20/src/mnemonic/wordlist
creating mnemonic-0.20/tests
creating mnemonic-0.20/tools
copying files to mnemonic-0.20...
copying .editorconfig -> mnemonic-0.20
copying .gitignore -> mnemonic-0.20
copying AUTHORS -> mnemonic-0.20
copying CHANGELOG.rst -> mnemonic-0.20
copying LICENSE -> mnemonic-0.20
copying MANIFEST.in -> mnemonic-0.20
copying Makefile -> mnemonic-0.20
copying README.rst -> mnemonic-0.20
copying setup.cfg -> mnemonic-0.20
copying setup.py -> mnemonic-0.20
copying tox.ini -> mnemonic-0.20
copying vectors.json -> mnemonic-0.20
copying .github/workflows/python-package.yml -> mnemonic-0.20/.github/workflows
copying .github/workflows/style-check.yml -> mnemonic-0.20/.github/workflows
copying src/mnemonic/__init__.py -> mnemonic-0.20/src/mnemonic
copying src/mnemonic/mnemonic.py -> mnemonic-0.20/src/mnemonic
copying src/mnemonic/py.typed -> mnemonic-0.20/src/mnemonic
copying src/mnemonic.egg-info/PKG-INFO -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/SOURCES.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/dependency_links.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/not-zip-safe -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/top_level.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic/wordlist/chinese_simplified.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/chinese_traditional.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/czech.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/english.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/french.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/italian.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/japanese.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/korean.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/portuguese.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/russian.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/spanish.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/turkish.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying tests/test_mnemonic.py -> mnemonic-0.20/tests
copying tools/generate_vectors.py -> mnemonic-0.20/tools
Writing mnemonic-0.20/setup.cfg
creating dist
Creating tar archive
removing 'mnemonic-0.20' (and everything under it)

jonny in python-mnemonic on  master via 🐍 v3.11.4
❯ tar tzf dist/mnemonic-0.20.tar.gz
mnemonic-0.20/
mnemonic-0.20/.editorconfig
mnemonic-0.20/.github/
mnemonic-0.20/.github/workflows/
mnemonic-0.20/.github/workflows/python-package.yml
mnemonic-0.20/.github/workflows/style-check.yml
mnemonic-0.20/.gitignore
mnemonic-0.20/AUTHORS
mnemonic-0.20/CHANGELOG.rst
mnemonic-0.20/LICENSE
mnemonic-0.20/MANIFEST.in
mnemonic-0.20/Makefile
mnemonic-0.20/PKG-INFO
mnemonic-0.20/README.rst
mnemonic-0.20/setup.cfg
mnemonic-0.20/setup.py
mnemonic-0.20/src/
mnemonic-0.20/src/mnemonic/
mnemonic-0.20/src/mnemonic/__init__.py
mnemonic-0.20/src/mnemonic/mnemonic.py
mnemonic-0.20/src/mnemonic/py.typed
mnemonic-0.20/src/mnemonic/wordlist/
mnemonic-0.20/src/mnemonic/wordlist/chinese_simplified.txt
mnemonic-0.20/src/mnemonic/wordlist/chinese_traditional.txt
mnemonic-0.20/src/mnemonic/wordlist/czech.txt
mnemonic-0.20/src/mnemonic/wordlist/english.txt
mnemonic-0.20/src/mnemonic/wordlist/french.txt
mnemonic-0.20/src/mnemonic/wordlist/italian.txt
mnemonic-0.20/src/mnemonic/wordlist/japanese.txt
mnemonic-0.20/src/mnemonic/wordlist/korean.txt
mnemonic-0.20/src/mnemonic/wordlist/portuguese.txt
mnemonic-0.20/src/mnemonic/wordlist/russian.txt
mnemonic-0.20/src/mnemonic/wordlist/spanish.txt
mnemonic-0.20/src/mnemonic/wordlist/turkish.txt
mnemonic-0.20/src/mnemonic.egg-info/
mnemonic-0.20/src/mnemonic.egg-info/PKG-INFO
mnemonic-0.20/src/mnemonic.egg-info/SOURCES.txt
mnemonic-0.20/src/mnemonic.egg-info/dependency_links.txt
mnemonic-0.20/src/mnemonic.egg-info/not-zip-safe
mnemonic-0.20/src/mnemonic.egg-info/top_level.txt
mnemonic-0.20/tests/
mnemonic-0.20/tests/test_mnemonic.py
mnemonic-0.20/tools/
mnemonic-0.20/tools/generate_vectors.py
mnemonic-0.20/tox.ini
mnemonic-0.20/vectors.json
```

### Works fine with Python 3.7:
```
jonny in python-mnemonic on  master via 🐍 v3.7.16 (py37)
❯ make clean
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
rm -fr .tox/
rm -f .coverage
rm -fr htmlcov/
rm -fr .pytest_cache

jonny in python-mnemonic on  master via 🐍 v3.7.16 (py37)
❯ python --version
Python 3.7.16

jonny in python-mnemonic on  master via 🐍 v3.7.16 (py37)
❯ python setup.py sdist
running sdist
running egg_info
creating src/mnemonic.egg-info
writing src/mnemonic.egg-info/PKG-INFO
writing dependency_links to src/mnemonic.egg-info/dependency_links.txt
writing top-level names to src/mnemonic.egg-info/top_level.txt
writing manifest file 'src/mnemonic.egg-info/SOURCES.txt'
reading manifest file 'src/mnemonic.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
adding license file 'AUTHORS'
writing manifest file 'src/mnemonic.egg-info/SOURCES.txt'
running check
creating mnemonic-0.20
creating mnemonic-0.20/src
creating mnemonic-0.20/src/mnemonic
creating mnemonic-0.20/src/mnemonic.egg-info
creating mnemonic-0.20/src/mnemonic/wordlist
creating mnemonic-0.20/tests
creating mnemonic-0.20/tools
copying files to mnemonic-0.20...
copying AUTHORS -> mnemonic-0.20
copying CHANGELOG.rst -> mnemonic-0.20
copying LICENSE -> mnemonic-0.20
copying MANIFEST.in -> mnemonic-0.20
copying README.rst -> mnemonic-0.20
copying setup.cfg -> mnemonic-0.20
copying setup.py -> mnemonic-0.20
copying tox.ini -> mnemonic-0.20
copying src/mnemonic/__init__.py -> mnemonic-0.20/src/mnemonic
copying src/mnemonic/mnemonic.py -> mnemonic-0.20/src/mnemonic
copying src/mnemonic/py.typed -> mnemonic-0.20/src/mnemonic
copying src/mnemonic.egg-info/PKG-INFO -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/SOURCES.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/dependency_links.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/not-zip-safe -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic.egg-info/top_level.txt -> mnemonic-0.20/src/mnemonic.egg-info
copying src/mnemonic/wordlist/chinese_simplified.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/chinese_traditional.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/czech.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/english.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/french.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/italian.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/japanese.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/korean.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/portuguese.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/russian.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/spanish.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying src/mnemonic/wordlist/turkish.txt -> mnemonic-0.20/src/mnemonic/wordlist
copying tests/test_mnemonic.py -> mnemonic-0.20/tests
copying tools/generate_vectors.py -> mnemonic-0.20/tools
Writing mnemonic-0.20/setup.cfg
creating dist
Creating tar archive
removing 'mnemonic-0.20' (and everything under it)

jonny in python-mnemonic on  master via 🐍 v3.7.16 (py37)
❯ tar tzf dist/mnemonic-0.20.tar.gz
mnemonic-0.20/
mnemonic-0.20/AUTHORS
mnemonic-0.20/CHANGELOG.rst
mnemonic-0.20/LICENSE
mnemonic-0.20/MANIFEST.in
mnemonic-0.20/PKG-INFO
mnemonic-0.20/README.rst
mnemonic-0.20/setup.cfg
mnemonic-0.20/setup.py
mnemonic-0.20/src/
mnemonic-0.20/src/mnemonic/
mnemonic-0.20/src/mnemonic/__init__.py
mnemonic-0.20/src/mnemonic/mnemonic.py
mnemonic-0.20/src/mnemonic/py.typed
mnemonic-0.20/src/mnemonic/wordlist/
mnemonic-0.20/src/mnemonic/wordlist/chinese_simplified.txt
mnemonic-0.20/src/mnemonic/wordlist/chinese_traditional.txt
mnemonic-0.20/src/mnemonic/wordlist/czech.txt
mnemonic-0.20/src/mnemonic/wordlist/english.txt
mnemonic-0.20/src/mnemonic/wordlist/french.txt
mnemonic-0.20/src/mnemonic/wordlist/italian.txt
mnemonic-0.20/src/mnemonic/wordlist/japanese.txt
mnemonic-0.20/src/mnemonic/wordlist/korean.txt
mnemonic-0.20/src/mnemonic/wordlist/portuguese.txt
mnemonic-0.20/src/mnemonic/wordlist/russian.txt
mnemonic-0.20/src/mnemonic/wordlist/spanish.txt
mnemonic-0.20/src/mnemonic/wordlist/turkish.txt
mnemonic-0.20/src/mnemonic.egg-info/
mnemonic-0.20/src/mnemonic.egg-info/PKG-INFO
mnemonic-0.20/src/mnemonic.egg-info/SOURCES.txt
mnemonic-0.20/src/mnemonic.egg-info/dependency_links.txt
mnemonic-0.20/src/mnemonic.egg-info/not-zip-safe
mnemonic-0.20/src/mnemonic.egg-info/top_level.txt
mnemonic-0.20/tests/
mnemonic-0.20/tests/test_mnemonic.py
mnemonic-0.20/tools/
mnemonic-0.20/tools/generate_vectors.py
mnemonic-0.20/tox.ini
```

**Comment by hegjon** [comment] 2023-08-13 21:04
Looks like it happens when `setuptools-scm` is installed and not related to the Python version.

**Comment by hegjon** [comment] 2023-08-14 09:05
`setuptools-scm` have hooks that will be executed automaticly by the module being installed.. the devs view it as a feature: https://github.com/pypa/setuptools_scm#file-finders-hook-makes-most-of-manifestin-unnecessary

**Comment by matejcik** [comment] 2023-08-14 09:11
Putting all version-tracked files in the sdist honestly looks rather reasonable. Is this a problem in some way? If not, I would close the issue with "working as intended".

**Comment by hegjon** [comment] 2023-08-14 09:39
More like a notice/documentation, if one maintainer relays on releasing with `setuptools-scm` and another does not, then there might cause issues in the future.

**Comment by matejcik** [comment] 2024-01-05 10:29
in 0bd9d8df2a41eceaa74a5478b75e3c14f3c561a1 i'm switching to Poetry which no longer does this

**Closed by matejcik** 2024-01-05 10:29 UTC
